### ISSUE TITLE
Chapter 1 EXERCISE 8

### ISSUE THREAD

**Issue by illuz** [derlin/scala-for-the-impatient#1]
Why use `probablePrime(100, Random)`.
It take the 100 bit as the first argument, and get 20 length string.

I try to understand it:

`(36^19) + 1` gets 0b100101011111100110000011110101110100000011111111111010101100100000000000000000000000000000000000001, it has 99 bit length.
`36^20` gets 0b10101000101110001011010001010010001010010001111111101000001000010000000000000000000000000000000000000000, it has 104 bit length.

**So 99, 100, 101, 102, 103, 104 bit length binary take every part of 20-length string.**
**100~103 length numbers always have 20 string length after `toString(36)`. And 99, 104 will partly convert to 19 or 20 or 21 length string.**

So if the 100 bit length the correct answer to this question? It only has part of the 20-length-string's full space.
I use another answer:
```
  // 8.
  // Random.alphanumeric random char stream
  // .take(20) take 20 item
  // .mkString to string
  // .toLowerCase to lower case
  println(Random.alphanumeric.take(20).mkString.toLowerCase)
```

**Comment by derlin** [comment]
illuz, thank you for your feedback. 

The answer you propose is indeed more elegant and generic. However, I tried to stick to the hints left in the question: 

> One way to create random file or directory names is to produce a *random BigInt* and *convert it to base 36*, yielding a string such as “qsnvbevtomcj38o06kul”. Poke around Scaladoc to find a way of doing this in Scala.

It suggests using a random `BigInt` and convert it to base 36, which are exactly the steps in my answer. Of course, this is only a basic exercise and here we don't care about genericity (so the length of the answer doesn't really matter).  I am also not a scala expert, just an interested student. 

To me, the fact that you found this answer proves you can definitely go to the next exercises (or even skip Chapter 1 ;) ).

Cheers,
Derlin

**Comment by illuz** [comment]
Thanks for replying and encouragement!
I get your point and I am going on to the next characters.
